### ISSUE TITLE
Design Docs Review

### ISSUE THREAD

**Issue by kkossally** [IvanGit911/MidGreen#1]
- [x] You should not use the name of the original site in your app's name.

- [x] Use more precise, professional language in your MVP list.

- [x] Every MVP should have a 2-3 bullet point description.

- [x] Make search its own bonus MVP rather than a part of the stories MVP.

- [x] Medium only has likes (a.k.a. 'claps'), not downvotes. Users should not be able to like a story more than once.

- [x] The parent_comment_id column should be allowed to be null.

- [x] Add frontend and backend routes.

- [x] Your use of both journals and stories is somewhat confusing. Pick one term.

**Comment by IvanGit911** [comment]
Hi, Kafele, I have a question in backend routes. Can I have two journal index nested under users and categories?
Like:
/users/id/journals
/categories/id/journals
