### ISSUE TITLE
W12D1 PM review

### ISSUE THREAD

**Issue by IvanGit911** [IvanGit911/MidGreen#2]
Hi, Kafele, I fixed all the previous issue.

I worked on my final project for some during weekends. 
I also have some questions.
1: I tried to come up with the way to let user log in with username or email. I think I figured out the back end part, but really confused about front end. Can you give me some suggestions?
2. I think I messed up git branches... Is there any way to set git status to original? I am afraid to try the cmd I found online.
Appreciated.

**Comment by kkossally** [comment]
- Save the dual option login for a bonus feature, as we discussed.

- What was the git command?
