### ISSUE TITLE
PM review #3

### ISSUE THREAD

**Issue by IvanGit911** [IvanGit911/MidGreen#3]
Hi, Kafele,

If you have time, could you please go through my website and give me some advice on how to improve?
I have pushed the most recent features to Heroku. 

I want to try to finish all seven required MVPs first before I dry my code, because I am really not sure whether I could finish all the things on time.

Thank you so much!

**Comment by kkossally** [comment]
- Your signup/logout/login functionality is almost error free. Nice work!

- I like your splash template, it will look great once you finish it.

- You have a bit of styling to do.

- [ ] the dropdown doesn't close after the user logs out

- [ ] submitting a session form with the enter key works, but registers an error in the console

- [ ] clear your errors when a user successfully logs in or signs up

- [ ] style your session errors to match Medium

- [ ] your category title index should not appear in the header on the splash page

- [ ] you should have footer on the splash page

- [ ] match the font, spacing, and position of your splash page elements to the original site

- [ ] [MINOR] make the logo not clickable when already on the root page
