### ISSUE TITLE
PM review #5 Comment MVP

### ISSUE THREAD

**Issue by IvanGit911** [IvanGit911/MidGreen#5]
Hi, Kafele, I finished my comments MVP and fixed almost all previous issues. But there are still some bugs. 

1. Even if the comment was successfully saved into the database, I have to hard fresh to let it show.
2. I fixed the z-index of the user dropdown, but the position somehow is now getting wield.
3. POPULAR ON MIDGREEN is still not sticky, even though I think I set the right style.
4. Edit and delete journal is still buggy, will work on that this afternoon.

Most of my test comments are the first journal under category: solar. I will seed more tonight before the presentation.

I believe the rest of the website should work as I expected.

Thanks for your time.

**Comment by kkossally** [comment]
- [ ] add padding to the inside of the comment text box so that the writing is not flush with the edge of the box

- [ ] the comments I add do not appear even after a refresh
